import cvttf_NotoSansCJK_Black
import cvttf_NotoSansCJK_Bold
import cvttf_NotoSansCJK_DemiLight
import cvttf_NotoSansCJK_Light
import cvttf_NotoSansCJK_Medium
import cvttf_NotoSansCJK_Regular
import cvttf_NotoSansCJK_Thin